import { repositoryMetadata } from "../../packages/conformance/src/evidenceScope.mjs";
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, mkdirSync, mkdtempSync, rmSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { tmpdir } from 'node:os';
import { spawnSync } from 'node:child_process';
import { AUTHORITY, SECONDARY, ROOT, project, serialize, verifyEquivalent, check, MODES } from './profile-c.mjs';
import { MANIFEST, verifyAuthority } from './verify-authority.mjs';
const source = JSON.parse(readFileSync(resolve(ROOT, AUTHORITY), 'utf8'));
const metadata = JSON.parse(readFileSync(resolve(ROOT, MANIFEST), 'utf8'));

test('committed projection is byte-exact, deterministic and read-only', () => {
  const before = readFileSync(resolve(ROOT, SECONDARY));
  check();check();
  assert.equal(serialize(project(source)), serialize(project(source)));
  assert.deepEqual(readFileSync(resolve(ROOT, SECONDARY)), before);
});
test('all modes explicitly map outcome/status/reason and preserve every other field', () => {
  const secondary = project(source);
  assert.deepEqual(secondary.vectors.map(v => v.id), source.vectors.map(v => v.id));
  for (const [i,v] of source.vectors.entries()) {
    const [status,reason] = MODES[v.mode];
    assert.deepEqual(secondary.vectors[i].expected, reason ? {status,reason} : {status});
    const {expected: ignored, ...fields} = secondary.vectors[i];
    const {expected: original, ...originalFields} = v;
    assert.deepEqual(fields, originalFields);
  }
  verifyEquivalent(source, secondary);
});
test('key insertion order is irrelevant to generation; vector order is preserved', () => {
  const reversed = Object.fromEntries(Object.entries(source).reverse());
  assert.equal(serialize(project(reversed)), serialize(project(source)));
  reversed.vectors = [...source.vectors].reverse();
  assert.deepEqual(project(reversed).vectors.map(v=>v.id), reversed.vectors.map(v=>v.id));
});
for (const [name, mutate] of [
  ['unknown outcome', s => s.vectors[0].expected.outcome = 'ALLOW'],
  ['incompatible mode/outcome', s => s.vectors[0].expected.outcome = 'compute-error'],
  ['unknown expected field', s => s.vectors[0].expected.reason = 'not in authority schema'],
  ['unknown mode', s => s.vectors[0].mode = 'future-mode'],
  ['unknown semantic field', s => s.vectors[0].new_semantics = true],
  ['duplicate ID', s => s.vectors.push(structuredClone(s.vectors[0]))],
  ['missing committed signature fixture', s => delete s.vectors[5].auth],
  ['unsupported strategy', s => s.vectors[0].hash_strategy = 'new-algorithm'],
]) test(`${name} is rejected, never silently projected`, () => {
  const s = structuredClone(source);mutate(s);assert.throws(()=>project(s));
});
for (const [name,mutate] of [
  ['changed status', p => p.vectors[0].expected.status = 'compute-error'],
  ['changed reason', p => p.vectors[1].expected.reason = 'different meaning'],
  ['missing vector', p => p.vectors.pop()],
  ['changed state', p => p.vectors[1].live_state_input.spent++],
  ['changed committed signature', p => p.vectors[5].auth.signature.sig = 'invalid'],
  ['missing authority metadata', p => delete p.outcomes],
]) test(`semantic verification rejects ${name}`, () => {
  const p=project(source);mutate(p);assert.throws(()=>verifyEquivalent(source,p));
});
test('format-only drift fails exact-byte CI check without changing any file', () => {
  const root=mkdtempSync(resolve(tmpdir(),'oxdeai-projection-'));
  try {
    for (const path of [AUTHORITY,SECONDARY]) {
      mkdirSync(dirname(resolve(root,path)),{recursive:true});
      writeFileSync(resolve(root,path),readFileSync(resolve(ROOT,path)));
    }
    check(root);
    const changed=JSON.stringify(project(source));
    writeFileSync(resolve(root,SECONDARY),changed);
    assert.throws(()=>check(root),/generated bytes drift/);
    assert.equal(readFileSync(resolve(root,SECONDARY),'utf8'),changed);
  } finally {rmSync(root,{recursive:true,force:true});}
});
test('authority inventory covers every release vector file, with only Profile-C projected',()=>{
  const rows=verifyAuthority(metadata);
  assert.equal(rows.filter(r=>r.representations.length>1).length,1);
  assert.equal(rows.find(r=>r.corpus==='profile-c').authority,AUTHORITY);
});
for(const [name,mutate] of [
  ['two authorities', m=>m.corpora[0].authority=[m.corpora[0].authority]],
  ['duplicate corpus', m=>m.corpora.push(structuredClone(m.corpora[0]))],
  ['missing corpus', m=>m.corpora.splice(0,1)],
  ['stale consumer', m=>m.corpora[0].consumers[0].binding='removed-corpus.json'],
  ['incorrect Profile-C direction',m=>{const c=m.corpora.find(c=>c.id==='profile-c');c.authority=SECONDARY;}],
  ['independent editable secondary',m=>m.corpora.find(c=>c.id==='profile-c').representations[1].generated=false],
]) test(`authority checker rejects ${name}`,()=>{
  const m=structuredClone(metadata);mutate(m);assert.throws(()=>verifyAuthority(m));
});
test('existing Profile-C signed payloads do not exercise disputed escaping',()=>{
  const plain = v => {
    if(typeof v==='string') assert.match(v,/^[\x20-\x21\x23-\x5b\x5d-\x7e]*$/);
    else if(Array.isArray(v))v.forEach(plain);
    else if(v && typeof v==='object')for(const [k,x] of Object.entries(v)){plain(k);plain(x);}
  };
  for(const v of source.vectors){
    plain(v.state_input);plain(v.live_state_input);
    if(v.auth){const a=structuredClone(v.auth);delete a.signature.sig;plain(a);}
  }
});


test('real projection CLI returns non-zero for a changed secondary in an isolated tree', () => {
  const root=mkdtempSync(resolve(tmpdir(),'oxdeai-projection-cli-'));
  try {
    for(const path of [AUTHORITY, SECONDARY, 'scripts/corpus/profile-c.mjs', 'packages/conformance/src/evidenceScope.mjs']) {
      mkdirSync(dirname(resolve(root,path)),{recursive:true});
      writeFileSync(resolve(root,path),readFileSync(resolve(ROOT,path)));
    }
    writeFileSync(resolve(root, 'packages/conformance/evidence-metadata.json'), JSON.stringify(repositoryMetadata(ROOT)));
    const run=()=>spawnSync(process.execPath,[resolve(root,'scripts/corpus/profile-c.mjs'),'--check'],{encoding:'utf8'});
    let child=run();assert.ifError(child.error);assert.equal(child.status,0,child.stderr);
    const changed=project(source);changed.vectors[1].expected.reason='independent edit';
    writeFileSync(resolve(root,SECONDARY),serialize(changed));
    child=run();assert.ifError(child.error);assert.equal(child.status,1);
    assert.match(child.stderr,/semantic divergence/);
    assert.deepEqual(JSON.parse(readFileSync(resolve(root,AUTHORITY),'utf8')),source);
  } finally {rmSync(root,{recursive:true,force:true});}
});
