import { evidenceScope } from "../../packages/conformance/src/evidenceScope.mjs";
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';

export const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
export const AUTHORITY = 'docs/spec/test-vectors/profile-c-state-verification.json';
export const SECONDARY = 'packages/conformance/vectors/profile-c-state-verification.json';
export const MODES = {
  'live-state-match': ['ok'],
  'live-state-mismatch': ['state-hash-mismatch', 'computeStateHash(liveState) does not equal authorization.state_hash'],
  'hash-strategy-mismatch': ['state-hash-mismatch', 'provider hash committed; Core strategy used at verification produces a different hash'],
  'compute-throws': ['compute-error', 'computeStateHash threw; execution blocked fail-closed'],
  'toctou-stale-state': ['state-hash-mismatch', 'TOCTOU: live state has advanced since authorization was issued'],
  'encoding-b-live-state-match': ['ok'],
  'encoding-b-live-state-mismatch': ['state-hash-mismatch', 'Encoding B auth: live state mismatch detected at Profile C step 10'],
  'encoding-b-hash-strategy-mismatch': ['state-hash-mismatch', 'Encoding B auth: computeStateHash strategy mismatch produces different hash'],
};
const object = x => x !== null && typeof x === 'object' && !Array.isArray(x);
function keys(x, allowed, required = allowed) {
  assert.ok(object(x), 'expected object');
  assert.ok(Object.keys(x).every(k => allowed.includes(k)), `unsupported fields: ${Object.keys(x)}`);
  assert.ok(required.every(k => Object.hasOwn(x, k)), `missing required fields: ${required}`);
}
function sorted(value) {
  if (Array.isArray(value)) return value.map(sorted);
  if (object(value)) return Object.fromEntries(Object.keys(value).sort().map(k => [k, sorted(value[k])]));
  return value;
}
export const serialize = value => JSON.stringify(sorted(value), null, 2) + '\n';

export function project(source) {
  keys(source, ['version', 'profile', 'portable', 'description', 'hash_strategies', 'outcomes', 'encoding_b_notes', 'vectors']);
  assert.equal(source.profile, 'C'); assert.equal(source.portable, true);
  assert.ok(Array.isArray(source.vectors) && source.vectors.length, 'non-empty vectors required');
  const ids = new Set();
  const vectors = source.vectors.map(v => {
    keys(v, ['id', 'mode', 'description', 'state_input', 'live_state_input', 'hash_strategy', 'signing_strategy', 'verify_strategy', 'auth', 'opts', 'expected'], ['id', 'mode', 'description', 'expected']);
    assert.ok(typeof v.id === 'string' && v.id.length && !ids.has(v.id), 'missing/duplicate vector ID'); ids.add(v.id);
    assert.ok(Object.hasOwn(MODES, v.mode), `unsupported mode: ${v.mode}`);
    keys(v.expected, ['outcome']);
    const [status, reason] = MODES[v.mode];
    assert.equal(v.expected.outcome, status, `${v.id}: unsupported mode/outcome mapping`);
    if (v.mode.startsWith('encoding-b-')) {
      keys(v.opts, ['now', 'trustedKey']);
      assert.ok(object(v.auth) && object(v.opts.trustedKey), `${v.id}: committed auth/key required`);
    } else assert.ok(!Object.hasOwn(v, 'auth') && !Object.hasOwn(v, 'opts'), `${v.id}: auth/opts unsupported for pure modes`);
    if (v.mode === 'compute-throws') assert.equal(v.hash_strategy, 'throws');
    else {
      assert.ok(object(v.state_input), `${v.id}: state_input required`);
      for (const field of ['hash_strategy', 'signing_strategy', 'verify_strategy']) if (Object.hasOwn(v, field)) assert.ok(['core', 'provider'].includes(v[field]), `${v.id}: unsupported ${field}`);
    }
    return { ...structuredClone(v), expected: reason ? { status, reason } : { status } };
  });
  return { ...structuredClone(source), vectors };
}

export function verifyEquivalent(source, secondary) {
  const expected = project(source);
  assert.deepEqual(secondary, expected, 'Profile-C semantic divergence (including metadata, fixtures and diagnostic mapping)');
  const reconstructed = { ...structuredClone(secondary), vectors: secondary.vectors.map(v => ({ ...v, expected: { outcome: v.expected.status } })) };
  assert.deepEqual(reconstructed, source, 'lossy Profile-C projection');
}

export function check(root = ROOT) {
  const source = JSON.parse(readFileSync(resolve(root, AUTHORITY), 'utf8'));
  const bytes = readFileSync(resolve(root, SECONDARY), 'utf8');
  verifyEquivalent(source, JSON.parse(bytes));
  assert.equal(bytes, serialize(project(source)), 'Profile-C generated bytes drift; review authority then run pnpm project:profile-c');
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    assert.ok(process.argv.length === 3 && ['--check', '--write'].includes(process.argv[2]), 'usage: profile-c.mjs --check | --write');
    if (process.argv[2] === '--write') {
      const source = JSON.parse(readFileSync(resolve(ROOT, AUTHORITY), 'utf8'));
      writeFileSync(resolve(ROOT, SECONDARY), serialize(project(source)));
    }
    check(); console.log('Profile-C projection: PASS (representation consistency only)');
    console.log(JSON.stringify({ result: 'PASS', evidenceScope: evidenceScope({ kind: 'structural-only', consumer: 'scripts/corpus/profile-c.mjs', runtime: 'JavaScript' }) }));
  } catch (e) { console.error(`Profile-C projection: FAIL: ${e.message}`); process.exitCode = 1; }
}
